# Generated by Django 5.1.7 on 2025-08-30 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='The quantity of the item ordered.')),
                ('total_price', models.DecimalField(decimal_places=2, help_text='The total price for this order item (quantity * item price).', max_digits=10)),
                ('order_accepted', models.BooleanField(default=False, help_text='Indicates whether a chef has accepted the order.')),
                ('dispatched', models.BooleanField(default=False, help_text='Indicates whether the order has been dispatched for delivery.')),
                ('ordered_at', models.DateTimeField(auto_now_add=True, help_text='The timestamp when the order was placed.')),
                ('customer', models.ForeignKey(help_text='The user who placed the order.', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(help_text='The menu item that was ordered.', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='train.menu')),
                ('station', models.ForeignKey(help_text='The station where the order is being prepared.', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='train.station')),
            ],
            options={
                'ordering': ['-ordered_at'],
            },
        ),
    ]
