# Generated by Django 5.1.7 on 2025-08-30 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_completed',
            field=models.BooleanField(default=False, help_text='Indicates whether a chef has completed the order.'),
        ),
    ]
